# SciPy – Teaching Notebook

This notebook introduces **SciPy** with clear explanations and examples for classroom teaching.

---


## 1. Introduction to SciPy

SciPy is a Python library used for scientific and mathematical computing. It is built on top of NumPy and provides high-level functions for:

- Linear Algebra
- Optimization
- Integration
- Statistics
- Sparse Matrices

SciPy is widely used as an alternative to tools like MATLAB and R for scientific computing.


In [1]:
import numpy as np
from scipy import linalg, integrate, sparse

## 2. Linear Algebra with SciPy

### Determinant of a Matrix

The determinant is a scalar value that represents certain properties of a matrix.

In [2]:
A = np.array([[1,2,3],[4,5,6],[7,8,8]])
linalg.det(A)

np.float64(2.999999999999997)

### LU Decomposition

LU decomposition breaks a matrix into:

- **P** → Permutation matrix
- **L** → Lower triangular matrix
- **U** → Upper triangular matrix

This is useful for solving linear systems efficiently.

In [3]:
P, L, U = linalg.lu(A)
P, L, U

(array([[0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]]),
 array([[1.        , 0.        , 0.        ],
        [0.14285714, 1.        , 0.        ],
        [0.57142857, 0.5       , 1.        ]]),
 array([[7.        , 8.        , 8.        ],
        [0.        , 0.85714286, 1.85714286],
        [0.        , 0.        , 0.5       ]]))

### Eigenvalues and Eigenvectors

Eigenvalues represent the scaling factor, and eigenvectors represent the direction.

In [4]:
eigen_values, eigen_vectors = linalg.eig(A)
eigen_values, eigen_vectors

(array([15.55528261+0.j, -1.41940876+0.j, -0.13587385+0.j]),
 array([[-0.24043423, -0.67468642,  0.51853459],
        [-0.54694322, -0.23391616, -0.78895962],
        [-0.80190056,  0.70005819,  0.32964312]]))

### Solving Linear Equations

Solve the system **Ax = b** using SciPy.

In [5]:
v = np.array([[2],[3],[5]])
linalg.solve(A, v)

array([[-2.33333333],
       [ 3.66666667],
       [-1.        ]])

## 3. Sparse Linear Algebra

Sparse matrices save memory when most elements are zero.

In [6]:
A_sparse = sparse.lil_matrix((1000, 1000))
A_sparse[0, :100] = np.random.rand(100)
A_sparse[1, 100:200] = A_sparse[0, :100]
A_sparse.setdiag(np.random.rand(1000))
A_sparse

<List of Lists sparse matrix of dtype 'float64'
	with 1199 stored elements and shape (1000, 1000)>

### Solving Sparse Linear Systems

In [ ]:
A_csr = A_sparse.tocsr()
b = np.random.rand(1000)
from scipy.sparse.linalg import spsolve
spsolve(A_csr, b)

## 4. Numerical Integration

When analytical integration is difficult, we use numerical methods.

### Single Integral using quad

In [ ]:
f = lambda x: np.exp(-x**2)
integrate.quad(f, 0, 1)


f = lambda y, x: x * y**2
integrate.dblquad(f, 0, 2, lambda x: 0, lambda x: 1)

### Double Integral using dblquad

Example: Integrate **x * y²** where:

- x ranges from 0 to 2
- y ranges from 0 to 1

## 5. Summary

In this notebook, we covered:

- SciPy basics
- Linear Algebra operations
- Sparse matrices
- Numerical integration

This foundation is essential for **Data Science**, **Machine Learning**, and **Scientific Computing**.